# Nexys4 Pin Assignments
############################
# On-board Slide Switches  #
############################
set_property PACKAGE_PIN E3 [get_ports clk_100mhz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100mhz]
set_property PACKAGE_PIN U9 [get_ports power]
set_property IOSTANDARD LVCMOS33 [get_ports power]
set_property PACKAGE_PIN U8 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN P4 [get_ports RAM_addr_3]
set_property IOSTANDARD LVCMOS33 [get_ports RAM_addr_3]
set_property PACKAGE_PIN P3 [get_ports RAM_addr_2]
set_property IOSTANDARD LVCMOS33 [get_ports RAM_addr_2]
set_property PACKAGE_PIN R3 [get_ports RAM_addr_1]
set_property IOSTANDARD LVCMOS33 [get_ports RAM_addr_1]
set_property PACKAGE_PIN T1 [get_ports RAM_addr_0]
set_property IOSTANDARD LVCMOS33 [get_ports RAM_addr_0]
set_property PACKAGE_PIN T3 [get_ports sec1]
set_property IOSTANDARD LVCMOS33 [get_ports sec1]
set_property PACKAGE_PIN U2 [get_ports sec0]
set_property IOSTANDARD LVCMOS33 [get_ports sec0]


############################
# On-board led             #
############################

set_property PACKAGE_PIN N6 [get_ports location[0]]
set_property IOSTANDARD LVCMOS33 [get_ports location[0]]
set_property PACKAGE_PIN M6 [get_ports location[1]]
set_property IOSTANDARD LVCMOS33 [get_ports location[1]]
set_property PACKAGE_PIN M3 [get_ports location[2]]
set_property IOSTANDARD LVCMOS33 [get_ports location[2]]
set_property PACKAGE_PIN N5 [get_ports location[3]]
set_property IOSTANDARD LVCMOS33 [get_ports location[3]]
set_property PACKAGE_PIN N2 [get_ports location[4]]
set_property IOSTANDARD LVCMOS33 [get_ports location[4]]
set_property PACKAGE_PIN N4 [get_ports location[5]]
set_property IOSTANDARD LVCMOS33 [get_ports location[5]]
set_property PACKAGE_PIN L1 [get_ports location[6]]
set_property IOSTANDARD LVCMOS33 [get_ports location[6]]
set_property PACKAGE_PIN M1 [get_ports location[7]]
set_property IOSTANDARD LVCMOS33 [get_ports location[7]]

set_property PACKAGE_PIN L3 [get_ports temp[0]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[0]]
set_property PACKAGE_PIN N1 [get_ports temp[1]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[1]]
set_property PACKAGE_PIN L5 [get_ports temp[2]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[2]]
set_property PACKAGE_PIN L4 [get_ports temp[3]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[3]]
set_property PACKAGE_PIN K3 [get_ports temp[4]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[4]]
set_property PACKAGE_PIN M2 [get_ports temp[5]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[5]]
set_property PACKAGE_PIN L6 [get_ports temp[6]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[6]]
set_property PACKAGE_PIN M4 [get_ports temp[7]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[7]]
