# Nexys4 Pin Assignments
############################
# On-board Slide Switches  #
############################
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN U9 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN U8 [get_ports set]
set_property IOSTANDARD LVCMOS33 [get_ports set]
set_property PACKAGE_PIN R7 [get_ports online]
set_property IOSTANDARD LVCMOS33 [get_ports online]
set_property PACKAGE_PIN R6 [get_ports C_more]
set_property IOSTANDARD LVCMOS33 [get_ports C_more]
set_property PACKAGE_PIN R5 [get_ports M_more]
set_property IOSTANDARD LVCMOS33 [get_ports M_more]
set_property PACKAGE_PIN V7 [get_ports PQm]
set_property IOSTANDARD LVCMOS33 [get_ports PQm]
set_property PACKAGE_PIN V6 [get_ports PQc]
set_property IOSTANDARD LVCMOS33 [get_ports PQc]
set_property PACKAGE_PIN V5 [get_ports C_noCar]
set_property IOSTANDARD LVCMOS33 [get_ports C_noCar]
set_property PACKAGE_PIN U4 [get_ports M_noCar]
set_property IOSTANDARD LVCMOS33 [get_ports M_noCar]


############################
# On-board led             #
############################
set_property PACKAGE_PIN P2 [get_ports R_light]
set_property IOSTANDARD LVCMOS33 [get_ports R_light]
set_property PACKAGE_PIN R2 [get_ports G_light]
set_property IOSTANDARD LVCMOS33 [get_ports G_light]
set_property PACKAGE_PIN U1 [get_ports Y_light]
set_property IOSTANDARD LVCMOS33 [get_ports Y_light]
set_property PACKAGE_PIN P5 [get_ports R_light_c]
set_property IOSTANDARD LVCMOS33 [get_ports R_light_c]
set_property PACKAGE_PIN R1 [get_ports G_light_c]
set_property IOSTANDARD LVCMOS33 [get_ports G_light_c]
set_property PACKAGE_PIN V1 [get_ports Y_light_c]
set_property IOSTANDARD LVCMOS33 [get_ports Y_light_c]
set_property PACKAGE_PIN T8 [get_ports Power]
set_property IOSTANDARD LVCMOS33 [get_ports Power]


set_property PACKAGE_PIN N6 [get_ports location[0]]
set_property IOSTANDARD LVCMOS33 [get_ports location[0]]
set_property PACKAGE_PIN M6 [get_ports location[1]]
set_property IOSTANDARD LVCMOS33 [get_ports location[1]]
set_property PACKAGE_PIN M3 [get_ports location[2]]
set_property IOSTANDARD LVCMOS33 [get_ports location[2]]
set_property PACKAGE_PIN N5 [get_ports location[3]]
set_property IOSTANDARD LVCMOS33 [get_ports location[3]]
set_property PACKAGE_PIN N2 [get_ports location[4]]
set_property IOSTANDARD LVCMOS33 [get_ports location[4]]
set_property PACKAGE_PIN N4 [get_ports location[5]]
set_property IOSTANDARD LVCMOS33 [get_ports location[5]]
set_property PACKAGE_PIN L1 [get_ports location[6]]
set_property IOSTANDARD LVCMOS33 [get_ports location[6]]
set_property PACKAGE_PIN M1 [get_ports location[7]]
set_property IOSTANDARD LVCMOS33 [get_ports location[7]]

set_property PACKAGE_PIN L3 [get_ports temp[0]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[0]]
set_property PACKAGE_PIN N1 [get_ports temp[1]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[1]]
set_property PACKAGE_PIN L5 [get_ports temp[2]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[2]]
set_property PACKAGE_PIN L4 [get_ports temp[3]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[3]]
set_property PACKAGE_PIN K3 [get_ports temp[4]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[4]]
set_property PACKAGE_PIN M2 [get_ports temp[5]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[5]]
set_property PACKAGE_PIN L6 [get_ports temp[6]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[6]]
set_property PACKAGE_PIN M4 [get_ports temp[7]]
set_property IOSTANDARD LVCMOS33 [get_ports temp[7]]
